name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    - name: Build with Gradle
      run: ./gradlew build

    # Uncomment below to run tests
    # - name: Run Tests
    #   run: ./gradlew test

    # Optionally, upload APK/AAB as artifact
    # - name: Upload APK
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: app-release.apk
    #     path: app/build/outputs/apk/release/app-release.apk
